Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,24 +37,24 @@ jobs:
         run: npx ng build --configuration production --base-href "/pokedex-angular/"
 
       - name: Add .nojekyll file
-        run: echo "" > dist/pokedex/.nojekyll
+        run: echo "" > dist/pokedex/browser/.nojekyll
 
       - name: ✅ Check output directory content
         run: ls -lah dist/pokedex
+
       - name: ✅ Check output browser directory content
         run: ls -lah dist/pokedex/browser
 
       - name: ✅ Show index.html content
-        run: cat dist/pokedex/index.html || echo "❌ index.html NOT FOUND"
+        run: cat dist/pokedex/browser/index.html || echo "❌ index.html NOT FOUND"
 
       - name: Setup Pages
         uses: actions/configure-pages@v4
 
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
-          with:
-            path: ./dist/pokedex/browser
-
+        with:
+          path: ./dist/pokedex/browser
 
       - name: Deploy to GitHub Pages
         id: deployment
